DROP DATABASE IF EXISTS "chat_app";
CREATE DATABASE IF NOT EXISTS "chat_app";


DROP TABLE IF EXISTS "CHAT_GROUPS";
CREATE TABLE IF NOT EXISTS CHAT_GROUPS (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);

DROP TABLE IF EXISTS "CHAT_USERS";
CREATE TABLE IF NOT EXISTS CHAT_USERS (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE);

DROP TABLE IF EXISTS "chat_messages";
CREATE TABLE IF NOT EXISTS chat_messages (id INTEGER PRIMARY KEY AUTOINCREMENT, content TEXT NOT NULL, createdDate TEXT, user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, FOREIGN KEY (user_id) REFERENCES CHAT_USERS(id), FOREIGN KEY (group_id) REFERENCES CHAT_GROUPS(id));




INSERT INTO CHAT_USERS(username) VALUES("hoanglinh");
INSERT INTO CHAT_USERS(username) VALUES("thanhnguyen");
INSERT INTO CHAT_USERS(username) VALUES("phucnguyen");


INSERT INTO CHAT_GROUPS(name) VALUES("Work");
INSERT INTO CHAT_GROUPS(name) VALUES("Student");
INSERT INTO CHAT_GROUPS(name) VALUES("C++ Class");


SELECT m.id, content, createdDate, user_id, u.username, group_id, g.name FROM CHAT_MESSAGES m 
        JOIN  CHAT_GROUPS g ON m.group_id = g.id 
        JOIN CHAT_USERS u on m.user_id = u.id
        